[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

lib_deps =
  bblanchon/ArduinoJson
  ottowinter/ESPAsyncWebServer-esphome
  me-no-dev/AsyncElegantOTA
  adafruit/RTClib
  adafruit/DHT sensor library
  esphome/ESP32-HUB75-MatrixPanel-I2S-DMA
