[env:esp32-s3]
platform = espressif32
board = esp32s3_120_16_8-qio_opi
framework = arduino

extra_scripts = pre:tools/embed_web_assets.py

build_src_filter =
    +<*>

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partition_16mb_single_ota.csv

build_flags =
	; Web UI modes: 0=disabled, 1=minimal, 2=full
	-DWEB_UI_MODE=1
	; NOAA alert feature flag: 1=enabled, 0=disabled
	-DWXV_ENABLE_NOAA_ALERTS=1
	; Lunar feature flags: set to 0 to remove lunar calendar / luck screens
	-DWXV_ENABLE_LUNAR_CALENDAR=1
	-DWXV_ENABLE_LUNAR_LUCK=1
	; Astronomy feature flags: set to 0 to remove Sun & Moon and/or Sky Brief screens
	-DWXV_ENABLE_ASTRONOMY=1
	-DWXV_ENABLE_SKY_BRIEF=1
	; Next 24 hour prediction feature flag: set to 0 to remove the prediction screen
	-DWXV_ENABLE_NEXT24H_PREDICTION=1

    -DCORE_DEBUG_LEVEL=3

    -D_IR_ENABLE_DEFAULT_=false
    -DDECODE_NEC
    -DDECODE_SAMSUNG
    -DDECODE_LG
    -DDECODE_SONY
    -DDECODE_RC5
    -DDECODE_RC6

    -DWXV_DISPLAY_SPLIT=1

    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -DCONFIG_MBEDTLS_DYNAMIC_FREE_PEER_CERT=1
    -DCONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA=1
    -DCONFIG_MBEDTLS_DYNAMIC_FREE_CA_CERT=1
    -DCONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN=1
    -DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=2048

    ;-DARDUINO_USB_CDC_ON_BOOT=1

    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

lib_deps =
    bblanchon/ArduinoJson
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    adafruit/RTClib
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    arduino-libraries/Arduino_JSON@^0.2.0
    mikaeltulldahl/AsyncOta@^1.0.2
    crankyoldgit/IRremoteESP8266@^2.8.6
    sensirion/Sensirion I2C SCD4x@^1.1.0
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit BMP280 Library@^2.6.8
    olikraus/U8g2_for_Adafruit_GFX@^1.8.0
    knolleary/PubSubClient@^2.8
    https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
    links2004/WebSockets @ ^2.4.1
    https://github.com/earlephilhower/ESP8266Audio.git
