#pragma once
void updateGraphData();
void drawTemperatureHistoryScreen();
void drawHumidityHistoryScreen();
void drawCo2HistoryScreen();
void drawBaroHistoryScreen();
void drawPredictionScreen();
void tickTemperatureHistoryMarquee();
void tickHumidityHistoryMarquee();
void tickCo2HistoryMarquee();
void tickBaroHistoryMarquee();
void tickPredictionScreen();
void handlePredictionDownPress();
void handlePredictionUpPress();
